### ISSUE TITLE
Unable to connect to centrifugo server using nodejs client

### ISSUE THREAD

**Issue by manjeet-thadani** [centrifugal/centrifuge-js#91] opened 2019-07-22 06:36 UTC
I have created a sample code to connect to centrifugo server. I am not using running this code on browser. It is purely nodeJS code.
 Sample: 

```
const Centrifuge = require('centrifuge')

var channel = '<channel>';

var centrifuge = new Centrifuge('<Socket URL>')
// If used in HTML file    
// <script type="text/javascript" src="https://rawgit.com/centrifugal/centrifuge-js/master/dist/centrifuge.min.js"></script>

centrifuge.setToken('<token>')

centrifuge.on('connect', function (ctx) {
  console.log('Connected with client ID ' + ctx.client + ' over ' + ctx.transport + ' with data: ' + JSON.stringify(ctx.data))
})

centrifuge.on('message', function (data) {
  console.log(JSON.stringify(data))
  // echo data back to server.
  centrifuge.send(data)
})

centrifuge.on('disconnect', function (ctx) {
  console.log('Disconnected: ' + ctx.reason + (ctx.reconnect ? ', will try to reconnect' : ', wont try to reconnect'))
})

// show how many users currently in channel.
function showPresence(sub) {
  sub.presence().then(function (result) {
    var count = 0
    for (var key in result.presence) {
      count++
    }
    console.log('Now in this room: ' + count + ' clients')
  }, function (err) {
    console.log('Presence error: ' + JSON.stringify(err))
  })
}

// subscribe on channel and bind various event listeners. Actual
// subscription request will be firer after client will connect to
// Centrifugo and will be authorized.
var sub = centrifuge.subscribe(channel, handleMessage)
  .on('join', handleJoin)
  .on('leave', handleLeave)
  .on('unsubscribe', handleUnsubscribe)
  .on('subscribe', handleSubscribe)
  .on('error', handleSubscribeError)

centrifuge.connect()
showPresence(sub)

function handleSubscribe(ctx) {
  console.log('Subscribed on channel ' + ctx.channel + ' (resubscribed: ' + ctx.isResubscribe + ', recovered: ' + ctx.recovered + ')')
  if (ctx.isResubscribe) {
    showPresence(sub)
  }
}

function handleSubscribeError(err) {
  console.log('Error subscribing on channel ' + err.channel + ': ' + err.message)
}

function handleMessage(message) {
  console.log(message, '>>>>>>>>>>>>')
  var clientID
  if (message.info) {
    clientID = message.info.client
  } else {
    clientID = null
  }
  var inputText = JSON.stringify(message.data)
  console.log(inputText)
}

function handleJoin(message) {
  console.log('Client joined channel ' + this.channel + ' (uid ' + message.info['client'] + ', user ' + message.info['user'] + ')')
}

function handleLeave(message) {
  console.log('Client left channel ' + this.channel + ' (uid ' + message.info['client'] + ', user ' + message.info['user'] + ')')
}

function handleUnsubscribe(sub) {
  console.log('Unsubscribed from channel ' + sub.channel)
}

function getParam(name, url) {
  if (!url) url = 'https://github.com/centrifugal/centrifuge-js'
  name = name.replace(/[\[\]]/g, '\\$&')
  var regex = new RegExp('[?&]' + name + '(=([^&#]*)|&|#|$)')
  var results = regex.exec(url)
  if (!results) return null
  if (!results[2]) return ''
  return decodeURIComponent(results[2].replace(/\+/g, ' '))
}

if (getParam('disconnect') == '1') {
  function reconnect() {
    setTimeout(function () {
      centrifuge.disconnect()
      setTimeout(function () {
        reconnect()
      }, 11000)
    }, 4000)
  }
  reconnect()
}

if (getParam('publish') == '1') {
  var publishInterval = parseInt(getParam('publishInterval')) || 1000
  var counter = 0
  setInterval(function () {
    sub.publish({ 'input': counter.toString() }).then(function () {
    }, function (err) {
      console.log('Publish error: ' + JSON.stringify(err))
    })
    counter++
  }, publishInterval)
}
```

It always prints
`Presence error: {"code":0,"message":"timeout"}`

But if I use this code in HTML file, it gets connected.

How can I connect to centrifugo server with nodeJS code without using and HTML / Front end component?

I am using the following versions:

- centrifuge: 2.2.1
- nodeJS: v8.9.4
- NPM: 5.6.0

**Comment by FZambia** [comment] 2019-07-22 17:10
Hello, is there something useful in server logs? You can start Centrifugo with DEBUG log level using `--log_level=debug`.

**Comment by manjeet-thadani** [comment] 2019-07-23 07:40
Whenever I try to connect to the server using NodeJS code, it doesn't show any log in server. But, when I run this code inside HTML file server logs following data:

```
{"level":"debug","method":"GET","path":"/connection/websocket","addr":"192.168.144.1","duration":0.063118,"time":"2019-07-23T07:39:00Z","message":"http request"}
{"level":"debug","client":"631c9fea-2af1-440f-995b-527b0b3bf31d","transport":"websocket","time":"2019-07-23T07:39:00Z","message":"client connection established"}
{"level":"debug","client":"631c9fea-2af1-440f-995b-527b0b3bf31d","user":"e2e79a11-94ec-4a87-bb89-a002e7136801","time":"2019-07-23T07:39:00Z","message":"client authenticated"}
{"level":"debug","channel":"stats:5debf49f185d5beb66e30b","client":"631c9fea-2af1-440f-995b-527b0b3bf31d","user":"e2e79a11-94ec-4a87-bb89-a002e7136801","time":"2019-07-23T07:39:00Z","message":"client subscribed to channel"}
{"level":"info","client":"631c9fea-2af1-440f-995b-527b0b3bf31d","command":"id:3 method:PRESENCE params:\"{\\\"channel\\\":\\\"stats:5debf49f185d5beb66e30b\\\"}\" ","error":"108: not available","reply":"id:3 error:<code:108 message:\"not available\" > ","user":"e2e79a11-94ec-4a87-bb89-a002e7136801","time":"2019-07-23T07:39:00Z","message":"client command error"}
```

**Comment by FZambia** [comment] 2019-07-23 13:49
I've never focused on NodeJS while developing this library so some aspects of it should be improved. In this case you can set debug option in Centrifuge objects configuration to see what happens:

```
var centrifuge = new Centrifuge('ws://localhost:8000/connection/websocket', {
    debug: true
})
```

You will se sth like this:

```
...
client will connect to websocket endpoint
subscribing on <channel>
start connecting
Status disconnected -> connecting
No Websocket support and no SockJS configured, can not connect
```

So the problem is that Centrifuge can't find `Websocket` object. You need to install WebSocket dependency:

```
npm install ws
```

At this point you have 2 options. Explicitly pass WebSocket object to Centrifuge.

```javascript
const Centrifuge = require('centrifuge');
const WebSocket = require('ws');

var centrifuge = new Centrifuge('ws://localhost:8000/connection/websocket', {
    debug: true
    websocket: WebSocket
})
```

Or define it globally:

```javascript
const Centrifuge = require('centrifuge');
global.WebSocket = require('ws'); 

var channel = '<channel>';

var centrifuge = new Centrifuge('ws://localhost:8000/connection/websocket', {
    debug: true
})
```

Could you try this? In general this is of course must be in documentation - if this works for you then I'll update docs accordingly.

**Comment by FZambia** [comment] 2019-11-20 06:54
Closing, this information is in README, feel free to reopen in case of problems.

**Closed by FZambia** 2019-11-20 06:54 UTC
