### ISSUE TITLE
InvalidStateError: The connection has not been established yet

### ISSUE THREAD

**Issue by hudbrog** [centrifugal/centrifuge-js#57] opened 2018-04-17 09:34 UTC
In some cases (around 3000 issues in 10 days) users get "InvalidStateError: The connection has not been established yet" with the following stacktrace:
Error: InvalidStateError: The connection has not been established yet
  at SockJS.send(/template_new/js/vendor.js:1:282599)
  at Centrifuge.o._send(/template_new/js/vendor.js:1:306559)
  at Centrifuge.o._addMessage(/template_new/js/vendor.js:1:317492)
  at t(/template_new/js/vendor.js:1:310337)
  at XMLHttpRequest.a.onreadystatechange(/template_new/js/vendor.js:1:302822)
  at XMLHttpRequest.wrapped(/template_new/js/build.js:1:144236)

I was not able to reproduce it locally. From what I can tell, in most cases it happens when users leave the page open for some time (40mins - tens of hours). 
Sometimes, I see in console:
Couldn't get auth info from application 0
and seconds after that - error. 

Sometimes, I see xhr request for refreshed token error out, after that a successfull reconnect and that error:
10:38:13 POST /push/refresh/ [403] 
10:38:17 Couldn't get auth info from application 403
10:38:17 GET https://esports.mail.ru/ws/connection/info?t=1523875097257 [200]
10:38:18 POST /push/refresh/ [200]
10:38:18 POST /push/refresh/ [200]
10:38:18 Error: InvalidStateError: The connection has not been established yet

**Comment by FZambia** [comment] 2018-04-17 19:37
Hmm, theoretically this can be a SockJS bug - just googled around - there are some similar issues. Maybe we should check transport `readyState` when sending messages and reconnect in case of wrong status, i.e. sth like this:

```javascript
    if (this._transport.readyState !== 1) {
        this._disconnect('connection closed', true);
        return;
    }
    this._transport.send(JSON.stringify(messages));
```

But I am not sure this is the right fix for all scenarios where this thing happens.

**Comment by hudbrog** [comment] 2018-08-06 13:33
Is it possible to figure something out with that issue? We are still getting lots of errors like that, mostly like in the original stack trace.

**Comment by FZambia** [comment] 2018-08-06 19:09
I need some help from you to solve this as I can't reproduce it myself. Maybe you could log what message is being sent when `InvalidStateError` happens. Don't know will this help or not - but maybe message is the same and will give a tip on how to solve this.

**Comment by FZambia** [comment] 2018-08-06 20:06
You can also write me on Gitter (https://gitter.im/centrifugal/centrifugo) into PM - maybe after understanding how you are using client I will have more ideas on reproducing scenario.

**Comment by FZambia** [comment] 2019-02-04 12:07
There is a chance that with 2.1.1 this error won't reproduce.

**Comment by FZambia** [comment] 2019-05-25 11:19
Closing as I believe this was fixed.

**Closed by FZambia** 2019-05-25 11:19 UTC

**Comment by VitaliyDemchuk** [comment] 2020-11-17 10:33
> Closing as I believe this was fixed.

Hello. @FZambia . Please tell us more about how this bug was fixed. Maybe there are links to commits?

**Comment by FZambia** [comment] 2020-11-17 10:38
@VitaliyDemchuk hello, `centrifuge-js` now checks the state of underlying transport before sending any data: see [this line](https://github.com/centrifugal/centrifuge-js/blob/2.6.4/src/centrifuge.js#L389). As far as I remember this was part of refactoring during moving from v1 to v2.

Could you describe your situation – are you still using v1 client with v1 Centrifugo. Or already using latest versions and still have errors like this?
