### ISSUE TITLE
Last number of topics to subscribe

### ISSUE THREAD

**Issue by Hrishikesh-Bhagwat** [centrifugal/centrifuge-js#168] opened 2021-10-04 09:32 UTC
Hi... React App crashes when the number of topics subscribed is large (greater than 10). Some memory leak may be happening.

**Comment by FZambia** [comment] 2021-10-04 09:36
Hello, please provide a reproducing example. Without it this can be a leak anywhere.

**Comment by Hrishikesh-Bhagwat** [comment] 2021-10-04 10:05
![Screenshot_20211004-152908_Chrome](https://user-images.githubusercontent.com/79875904/135832050-be2f23e0-209a-491b-9496-b61bf0815ef9.jpg)

This is happening as the length of the list is greater than 10. On commenting the code for websocket it worked fine. I even had removed all listeners but it's not there in this code. Will update the comment if that is necessary. I removed it as I was trying different things. The error was in subscription step itself as the error threw up in the first useEffect itself when nothing was previously subscribed.

**Comment by FZambia** [comment] 2021-10-04 10:11
Post a full self-contained example that reproduces an issue without React involved. Its impossible to debug looking at screenshots with code.

**Comment by Hrishikesh-Bhagwat** [comment] 2021-10-04 11:15
Meaning you want just javascript?

**Comment by FZambia** [comment] 2021-10-04 11:25
Yeah, this will allow to exclude any React specific problems.

**Comment by FZambia** [comment] 2021-11-30 11:55
Closing due to no reproducing steps - may be a problem in app or React-specific.

**Closed by FZambia** 2021-11-30 11:55 UTC
