### ISSUE TITLE
Is any option to publish message to unsubscribed channel ? 

### ISSUE THREAD

**Issue by khvalov** [centrifugal/centrifuge-js#55] opened 2018-03-10 18:20 UTC
Is any workaround/option to publish message to unsubscribed channel ?

**Comment by FZambia** [comment] 2018-03-10 19:06
@khvalov you can publish over backend, it's impossible from client side

**Comment by khvalov** [comment] 2018-03-11 14:46
@FZambia Is it somehow hardcoded on server side ? (seems not, because API calls works). So if it's not hadrcoded - workaround may be adjust your client lib on my own for my business purposes. 

Thanks

**Comment by FZambia** [comment] 2018-03-11 15:03
There is a [check](https://github.com/centrifugal/centrifugo/blob/master/libcentrifugo/conns/clientconn/conn.go#L903) on server side that client is subscribed on channel when it publishes a message. So a fix on client side only can't help here.

Can you describe why you can't subscribe on channel before publish to it in your case?

**Comment by FZambia** [comment] 2018-04-17 19:49
Closing as this is expected by design, @khvalov still interested what you ended up with regarded to this.

**Closed by FZambia** 2018-04-17 19:49 UTC
