### ISSUE TITLE
Resubscribe channel after reconnect even though channel has been unsubscribed before being disconnected

### ISSUE THREAD

**Issue by rlebosse** [centrifugal/centrifuge-js#46] opened 2017-11-22 15:12 UTC
I created a Centrifuge client with `retry: true`, `resubscribe: true` and connected it.

* I subscribe to a channel called `mychannel`.
* I unsubscribe the channel `mychannel`.
* Centrifuge client is disconnected (for instance Centrifugo server is stopped).
* Centrifuge client is reconnected (for instance Centrifugo server is started).
* Centrifuge client re-subscribes to the channel `mychannel`.

Is this normal considering the fact that I intentionnally unsubscribed this channel before the disconnection, meaning that I wanted it unsubscribed, even after the client disconnection-reconnection.

Thanks a lot !

**Comment by FZambia** [comment] 2017-11-22 18:14
Hello! Thanks for report! This looks like a bug - does this happen with latest client version?

**Comment by FZambia** [comment] 2017-11-25 13:27
@rlebosse thanks for pointing on this, I just merged a fix, will create new release soon

**Comment by rlebosse** [comment] 2017-11-28 10:13
@FZambia thanks for you reactivity !

I just tried centrifuge-js new version (1.4.7) and I'm facing another issue, which might be a consequence of fixing this one.

* I subscribe to a channel `ch1`.
* I subscribe to a channel `ch2`.
* Centrifuge client is disconnected (for instance Centrifugo server is stopped) : **in the console logs, I see that the client unsubscribes from channel `ch2` which should not happen**.
* Centrifuge client is reconnected (for instance Centrifugo server is started) : **the client resubscribes to the channel `ch1` but nothing happens with `ch2`**.

Do you know why it does so ? Do you want me to create a new issue to handle this bug ?
Thanks !

**Comment by FZambia** [comment] 2017-11-28 10:23
@rlebosse I will try to reproduce. At least how this must work:

* subscribe to a channel ch1
* subscribe to a channel ch2
* Centrifuge client is disconnected (for instance Centrifugo server is stopped) : in this case you must receive 2 unsubscribe events for channel ch1 and for channel ch2. And also disconnect event.
* Centrifuge client is reconnected - in this case both channels must resubscribe.

**Comment by FZambia** [comment] 2017-11-28 22:19
@rlebosse just reproduced and fixed - yes, that was introduced in 1.4.7.

There was an attempt to fix resubscribing when calling Centrifugo HTTP API unsubscribe method - but looks like it's not possible at moment and will be implemented in future with some changes on Centrifugo server side.

If you don't use HTTP API unsubscribe then things should work ok for you now.

**Comment by FZambia** [comment] 2017-11-29 07:39
The fix for HTTP API unsubscribe started [here](https://github.com/centrifugal/centrifugo/pull/198) - as soon as it released I will update this client.

**Comment by FZambia** [comment] 2018-08-14 20:37
Should be fixed in 1.5.0

**Closed by FZambia** 2018-08-14 20:37 UTC
